actors:
  roomcho:
    image_url: /images/actors/roomcho.jpg
    name: roomcho
    url: https://twitter.com/noruyama_noruo
  kakucho:
    image_url: /images/actors/kakucho.JPG
    name: kakucho
    url: https://twitter.com/high_toned
author: kakucho
description: 仲良しアラサー男子のヘラヘララジオ
description_long: 格調高く・ルーム長のアラサー男子2人が最近感じた"良いこと"をヘラヘラしながらお話するラジオ
email: migikara.chi@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: ミギチー
itunes_podcast_url:
keywords: 
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 右からチーする
url: https://chi-from-right-side.github.io/
